apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 27.0.2

    helm:
      values: |
        # Habilita el provider para Ingress nativos de Kubernetes
        additionalArguments:
          - "--providers.kubernetesingress=true"

        # Traefik será la IngressClass por defecto
        ingressClass:
          enabled: true
          isDefaultClass: true
          name: traefik

        # Configuración de puertos dentro del cluster
        ports:
          web:
            port: 80          # Puerto interno del Service
            exposedPort: 80   # Puerto expuesto dentro del cluster
            targetPort: 8000  # Puerto del pod Traefik (entrypoint web)
            expose: true

          websecure:
            port: 443
            exposedPort: 443
            targetPort: 8443  # Puerto del pod Traefik (entrypoint websecure)
            expose: true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
