apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matomo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: matomo
    targetRevision: 11.0.0
    helm:
      values: |
        global:
          imageRegistry: registry.bitnami.com

        image:
          registry: registry.bitnami.com
          repository: bitnami/matomo

        mariadb:
          image:
            registry: registry.bitnami.com
            repository: bitnami/mariadb

  destination:
    server: https://kubernetes.default.svc
    namespace: matomo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
